# Copyright Contributors to the Open Cluster Management project

FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.26 AS builder

WORKDIR /workspace

COPY go.mod go.mod
COPY go.sum go.sum
COPY cmd/main.go cmd/main.go
COPY api/ api/
COPY internal/ internal/
COPY pkg/common/ pkg/common/
COPY LICENSE LICENSE

RUN CGO_ENABLED=1 GOEXPERIMENT=strictfipsruntime go build -mod=readonly -o manager cmd/main.go

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

LABEL url="https://github.com/stolostron/dynamic-scoring-framework" \
      com.redhat.component="dynamic-scoring-controller-container" \
      summary="Dynamic Scoring Framework controller for Red Hat Advanced Cluster Management" \
      description="Dynamic Scoring Framework controller for Red Hat Advanced Cluster Management" \
      io.k8s.display-name="Dynamic Scoring Framework controller" \
      io.k8s.description="Dynamic Scoring Framework controller for Red Hat Advanced Cluster Management" \
      io.openshift.tags="acm dynamic-scoring-controller"

WORKDIR /
COPY --from=builder /workspace/manager /manager
COPY --from=builder /workspace/LICENSE /licenses/

USER 65532:65532

ENTRYPOINT ["/manager"]
