apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-scorer
  namespace: dynamic-scoring
  annotations:
    skupper.io/address: sample-scorer
    skupper.io/port: "8000"
    skupper.io/proxy: "tcp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-scorer
  template:
    metadata:
      labels:
        app: sample-scorer
    spec:
      containers:
        - name: sample-scorer
          image: quay.io/bjoydeep/sample-scorer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sample-scorer
  namespace: dynamic-scoring
spec:
  type: ClusterIP
  selector:
    app: sample-scorer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sample-scorer
  namespace: dynamic-scoring
spec:
  to:
    kind: Service
    name: sample-scorer
  port:
    targetPort: 8000
  wildcardPolicy: None